#adapted from example in docker documentation
version: '3'

services:
  redis:
    image: redis
    expose:
       - 6379
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8080
    command: python /code/tke_project/manage.py runserver 0.0.0.0:8080
    links:
       - redis
  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
    #  - "443:443"
#     volumes:
#        - ./mysite/myapp/static:/static
    links:
      - web:web
