#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 8080:8080
    command: python /code/tke_project/manage.py runserver 0.0.0.0:8080
