# Generated by Django 2.2.6 on 2019-10-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='post_author',
        ),
    ]
