# Generated by Django 2.2.6 on 2019-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('Image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateField(blank=True, default='2016-06-08', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='current_volunteers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='max_volunteers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='published_date',
            field=models.DateField(blank=True, default='2016-06-01', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
