# Generated by Django 2.2.6 on 2019-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='RUSH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lastName', models.TextField()),
                ('email', models.TextField()),
                ('year', models.TextField()),
                ('whyTke', models.TextField()),
            ],
        ),
    ]
