# Generated by Django 2.2.6 on 2019-11-23 18:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191121_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_author',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='rush',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+1', max_length=128, region=None),
        ),
    ]
