# Generated by Django 2.2.6 on 2019-11-26 19:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191123_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+1', max_length=128, region=None)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Event')),
            ],
            options={
                'ordering': ['email', 'phone_number', 'event'],
            },
        ),
    ]
