# Generated by Django 2.2.6 on 2019-11-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20191126_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['name', 'email', 'phone_number', 'event']},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='name',
            field=models.CharField(default='andres', max_length=100),
            preserve_default=False,
        ),
    ]
