# Generated by Django 2.2.6 on 2019-12-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191127_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Event'),
            preserve_default=False,
        ),
    ]
